### ISSUE TITLE
小节信息获取错误

### ISSUE THREAD

**Issue by leo-ashton** [HirokiChin/CqoocAutoCompleteCourse#18]
这是我的网课列表：
![image](https://user-images.githubusercontent.com/60648876/140591389-26a1cb5d-d7b3-44e7-80c1-fc15124e3d85.png)
![image](https://user-images.githubusercontent.com/60648876/140591411-12f9ba6a-9d22-455c-b41e-22ae7eada65e.png)
这是程序模拟观看的结果：
![image](https://user-images.githubusercontent.com/60648876/140591440-e1fc8c20-eed7-4947-ac1c-1599e456a585.png)
获取到的小节信息是错误的。

**Comment by FuJiangXun** [comment]
我运行了程序后网页端打开课程找不到学习内容
