### ISSUE TITLE
大佬脚本运行不了了

### ISSUE THREAD

**Issue by 200lii** [HirokiChin/CqoocAutoCompleteCourse#21]

**Comment by HirokiChin** [comment]
2021-12-13 15:40测试所有功能均正常

**Comment by 200lii** [comment]
大佬我从2021-12-9 开始Windows直接双击脚本运行，打开后出现闪退，我还没用Python IDLE运行，不知道大佬这是什么问题，希望大佬帮忙看看，我还有3课没刷完啊，救救我呀。

**Comment by classssss948** [comment]
大哥你好，那个刷课模式自动跳过已完成是不是有限制啊？我刷的时候他跳过到一定地方就不会跳过了，然后就会刷一部分重复的

**Comment by HirokiChin** [comment]
> 大哥你好，那个刷课模式自动跳过已完成是不是有限制啊？我刷的时候他跳过到一定地方就不会跳过了，然后就会刷一部分重复的

接口的bug，接口返回的已完成小节不全，所以有些课程会重复刷，不影响的

**Comment by classssss948** [comment]
> 

哦哦好谢谢大哥

**Comment by FuJiangXun** [comment]
大佬，就是我有一门网课还没进入过学习页面就直接用程序刷了，后来在网页打开课程的时候，课程里的学习内容显示暂无数据。

**Comment by classssss948** [comment]
大哥方便更新一下脚本吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HirokiChin/CqoocAutoCompleteCourse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月19日(星期天) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HirokiChin/CqoocAutoCompleteCourse] 大佬脚本运行不了了 (Issue #21)





  
大哥你好，那个刷课模式自动跳过已完成是不是有限制啊？我刷的时候他跳过到一定地方就不会跳过了，然后就会刷一部分重复的
  
接口的bug，接口返回的已完成小节不全，所以有些课程会重复刷，不影响的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
