### ISSUE TITLE
关于脚本最大单次只能获取150个已完成小节的修复思路询问

### ISSUE THREAD

**Issue by Mo-Yuxi** [HirokiChin/CqoocAutoCompleteCourse#22]
事先声明，鄙人仅为一名Python学习者
在刷某丑长臭长的网课时，发现程序只能获取到150个已完成列表，导致网课无法从靠后的位置直接进行继续刷课，故尝试进行修改
但是本人并无js与网络开发经验，故想请问几位作者，下述思路与修改是否正确
思路：
检查获取已完成小节信息的相关模块，发现源码492行左右的
`data = self.get(
            f'http://www.cqooc.com/json/learnLogs?limit=150&start=1&courseId={self.courseId}&select=sectionId&username={self.username}&ts={getTs()}', headers={
                "referer": f'http://www.cqooc.net/learn/mooc/structure?id={self.courseId}'
            })`
输入了参数limit = 150与 start = 1，本人最先尝试将limit修改为200、250，均被服务器403；
而后本人尝试在本次获取并将数据转存进CourseIdList后，修改程序流程，再次执行上述对data变量的获取，并将start = 1修改为 start = 151，以尝试获取第一次未能获取的部分，并再次将获取到的数据append至CourseIdList列表中，其余代码未修改。
经过上述修改，程序似乎可以从正确位置继续执行
但是本人账号仅有一个且该账号在150节之前的网课均已刷完，无法进行测试，故请问：
1.按照这个思路修改后  获取到的列表是否是正确的列表
2.按照上述办法修改代码会不会导致列表出现错乱
3.按照上述办法修改代码会不会导致被服务器记录（虽然我也不知道服务器是否有触发异常记录的功能）

**Comment by Mo-Yuxi** [comment]
修改后的代码块为
`def getCompleteCourse(self) -> list:
        """
        获取已完成小节列表
        :return:
        """
        self.Session.headers['Referer'] = 'http://www.cqooc.com/learn/mooc/progress?id=' + self.courseId
        data = self.get(
            f'http://www.cqooc.com/json/learnLogs?limit=150&start=1&courseId={self.courseId}&select=sectionId&username={self.username}&ts={getTs()}', headers={
                "referer": f'http://www.cqooc.net/learn/mooc/structure?id={self.courseId}'
            })
        CourseIdList = []
        for i in data.json()['data']:
            CourseIdList.append(i['sectionId'])
        data = self.get(
            f'http://www.cqooc.com/json/learnLogs?limit=150&start=151&courseId={self.courseId}&select=sectionId&username={self.username}&ts={getTs()}', headers={
                "referer": f'http://www.cqooc.net/learn/mooc/structure?id={self.courseId}'
            })
        for i in data.json()['data']:
            CourseIdList.append(i['sectionId'])
        return CourseIdList`

**Comment by Mo-Yuxi** [comment]
![123show](https://user-images.githubusercontent.com/80117830/146713036-26dee3d9-2b5a-46e7-93e9-650213fd480e.png)

**Comment by HirokiChin** [comment]
提供下你这门课的名称，我测试下

**Comment by Mo-Yuxi** [comment]
毛泽东思想和中国特色社会主义理论体系概论（第二次开课）
structure?id=334569178

**Comment by HirokiChin** [comment]
> 毛泽东思想和中国特色社会主义理论体系概论（第二次开课）
> structure?id=334569178
把你QQ发到我邮箱，我账号没有观看不好测试。
charles000317@gmail.com

**Comment by Mo-Yuxi** [comment]
最新版代码已解决问题，关闭issue
