### ISSUE TITLE
解决----关于无法答题的问题

### ISSUE THREAD

**Issue by EucalyZ** [HirokiChin/CqoocAutoCompleteCourse#32]
只需要将82行的地址从www.cqooc.net改成www.cqooc.com即可，如下图

![图片](https://user-images.githubusercontent.com/112610152/197215571-ecd20169-7d7c-4db1-81c8-0a2b3e3e46cd.png)

**Comment by censujiang** [comment]
改了也不行啊

**Comment by censujiang** [comment]
报错信息跟之前的不同了，是这个
```bash
Traceback (most recent call last):
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 590, in <module>
    AutoCompleteOnlineCourse().main()
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 436, in main
    autoCompletPapers.sendAnswers(mode='due')
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 312, in sendAnswers
    answers = self.getAnswers(id) if mode == 'due' else self.getAnswersFromUser(id)
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 225, in getAnswers
    ids = self.getIds(paperId)
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 81, in getIds
    "sid": self.sectionList.get(data.get('parentId'))[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by EucalyZ** [comment]
> 报错信息跟之前的不同了，是这个
> 
> ```shell
> Traceback (most recent call last):
>   File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 590, in <module>
>     AutoCompleteOnlineCourse().main()
>   File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 436, in main
>     autoCompletPapers.sendAnswers(mode='due')
>   File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 312, in sendAnswers
>     answers = self.getAnswers(id) if mode == 'due' else self.getAnswersFromUser(id)
>   File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 225, in getAnswers
>     ids = self.getIds(paperId)
>   File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 81, in getIds
>     "sid": self.sectionList.get(data.get('parentId'))[0]
> TypeError: 'NoneType' object is not subscriptable
> ```

还有其它的涉及到这个域名的，也改一下

**Comment by 55555ad** [comment]
![2023-05-18](https://github.com/HirokiChin/CqoocAutoCompleteCourse/assets/133984793/b5f66c6e-9a1a-4272-8677-c3cf2f3b5143)

还是不行
