### ISSUE TITLE
脚本运行一段时间就会闪退

### ISSUE THREAD

**Issue by JayyZ20** [HirokiChin/CqoocAutoCompleteCourse#5]
已经是更新最新的了

**Comment by HirokiChin** [comment]
使用终端/CMD运行此脚本，然后截图报错信息

**Comment by JayyZ20** [comment]
![QQ截图20201203194246](https://user-images.githubusercontent.com/75419862/101013823-c9923e00-355c-11eb-98f2-e972752dedf4.png)
额，这是什么意思？CQOOC那边太卡了？

**Comment by ghost** [comment]
运行闪退，终端模拟器打开也是闪退。

**Comment by HirokiChin** [comment]
刚测试，我使用没问题，要么是你网络有问题，要么就是重庆高校在线太卡啦

**Comment by xingxiya** [comment]
课程号我查出来以后报错哎

**Comment by JayyZ20** [comment]
我之前用你在吾爱的版本都是可以运行没有任何问题的，然后很长一段时间都没用了，最近更新了你的最新版本，用一会就会出现这样的状况（不排除是重庆高校太卡了，我有时候访问都很卡，网络环境我没换过，应该不是这个问题）而且xsid变得很快，老版本我刷了几个周都是一个xsid没有更换。现在新版本我打开几次后不换xsid就加载很慢，甚至等一会什么都没有就闪退（不知道是不是重庆高校这边有检测变化）emmm，还是很支持你，希望做得更好吧

**Comment by xiuxiudada** [comment]
作者大大，我也是同样的问题，报错都是一模一样的，能不能更新一下，自动重新执行

**Comment by HirokiChin** [comment]
最新的版本已经修复了此问题，如果依旧报错，请留下你们的邮箱

**Comment by JayyZ20** [comment]
570441676@qq.com
