### ISSUE TITLE
作者大大，你好 脚本的第3个功能无法使用，就是不能考试

### ISSUE THREAD

**Issue by xiuxiudada** [HirokiChin/CqoocAutoCompleteCourse#9]

**Comment by ningzhi123** [comment]
![屏幕截图 2020-12-13 231603](https://user-images.githubusercontent.com/65798868/102041817-5e255780-3e0b-11eb-85a6-3a63cb2c1911.png)
你有出现这种吗

**Comment by xiuxiudada** [comment]
> ![屏幕截图 2020-12-13 231603](https://user-images.githubusercontent.com/65798868/102041817-5e255780-3e0b-11eb-85a6-3a63cb2c1911.png)
> 你有出现这种吗

有，这是重庆高校服务器卡了

**Comment by ningzhi123** [comment]
不会吧，你知道咋解决吗

**Comment by HirokiChin** [comment]
如果一直出现问题的，留下邮箱，我发联系方式给你

**Comment by xiuxiudada** [comment]
mimosaxiu@qq.com

**Comment by xiuxiudada** [comment]
> 如果一直出现问题的，留下邮箱，我发联系方式给你

mimosaxiu@qq.com

**Comment by ningzhi123** [comment]
重新执行也会那样



---原始邮件---
发件人: "xiuxiudada"<notifications@github.com&gt;
发送时间: 2020年12月15日(周二) 晚上9:27
收件人: "HirokiChin/CqoocAutoCompleteCourse"<CqoocAutoCompleteCourse@noreply.github.com&gt;;
抄送: "ningzhi123"<2262223779@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [HirokiChin/CqoocAutoCompleteCourse] 作者大大，你好 脚本的第3个功能无法使用，就是不能考试 (#9)




  
如果一直出现问题的，留下邮箱，我发联系方式给你
  
mimosaxiu@qq.com
